import os
from collections import defaultdict

Import("env", "core_objs", "utils_obj", "lib_param_obj", "lib_analysis_obj", "lib_plot_obj")

all_objs = core_objs + utils_obj + lib_param_obj + lib_analysis_obj + lib_plot_obj

modenv = env.Clone()
modenv.AppendUnique(LINKFLAGS=[
    "-Wl,-soname,libCascade.so",
    r"-Wl,-rpath=\$$ORIGIN:\$$ORIGIN/../src:\$$ORIGIN/../utils:\$$ORIGIN/../AnalysisManager:\$$ORIGIN/../ParamManager:\$$ORIGIN/../PlotManager",
])
for obj in all_objs:
    if str(obj).endswith(".so"):
        libname = os.path.basename(obj.name)[3:-3]
        modenv.AppendUnique(LIBS=[libname])
        modenv.AppendUnique(LIBPATH=[os.path.dirname(str(obj))])


srcs = [
    "Cascade.cc",
    "PluginBindings.cc",
    "StateBindings.cc",
    "WorkflowBindings.cc",
]

lib = modenv.SharedLibrary("Cascade", srcs)
modenv.Depends(lib, all_objs)
install_targets = modenv.Install(modenv["LIBDIR"], lib)

Return("lib install_targets")
