#!/usr/bin/env python3
"""Cascade command-line entry point."""
import os
import sys


_ENTRYPOINT_DIR = os.path.dirname(os.path.realpath(__file__))
_CLI_PREFIX = os.environ.get("CASCADE_PREFIX", os.path.dirname(_ENTRYPOINT_DIR))
for _python_root in (os.path.join(_CLI_PREFIX, "lib"), _ENTRYPOINT_DIR):
    if os.path.isdir(os.path.join(_python_root, "cascade_cli")) and _python_root not in sys.path:
        sys.path.insert(0, _python_root)

from cascade_cli.main import main


if __name__ == "__main__":
    main()
