from typing import Any, Iterable, Optional
from . import RuntimeOptions

class WorkflowProvenanceError(RuntimeError):
    result: Any
    provenance_error: Exception

class Controller:
    last_workflow_provenance_path: str
    last_workflow_provenance_error: str
    def __init__(self, require_signed: bool = ..., discover_plugins: bool = ...,
                 runtime_options: Optional[RuntimeOptions] = ...) -> None: ...
    def refresh_plugins(self) -> dict[str, list[str]]: ...
    def register_module(self, class_name: str, name: Optional[str] = ...) -> Any: ...
    def register_python_module(self, name: str, module_obj: Any) -> Any: ...
    def run_module(self, name_or_mod: Any, isolated: bool = ...) -> Any: ...
    def run_module_isolated(self, name_or_mod: Any) -> Any: ...
    def get_list_available_modules(self) -> Any: ...
    def get_list_available_module_metadata(self, include_python: bool = ...,
                                           instantiate_python: bool = ...) -> Any: ...
    def get_list_registered_modules(self) -> Any: ...
    def get_status(self, name: str) -> str: ...
    def get_all_progress(self) -> Any: ...
    def get_module(self, name: str) -> Any: ...
    def get_python_module(self, name: str) -> Any: ...
    def get_dag(self) -> Any: ...
    def add_module_to_dag(self, name: str, dependencies: Optional[Iterable[str]] = ...,
                          isolated: bool = ...) -> None: ...
    def link_dag_parameter(self, from_node: str, from_key: str,
                           to_node: str, to_key: str) -> None: ...
    def run_dag(self, fail_fast: bool = ...,
                provenance_path: Optional[str] = ..., *, require_provenance: bool = ...) -> Any: ...
    def run_group(self, group: Iterable[Any], fail_fast: bool = ...) -> Any: ...
    def save_provenance(self, path: Optional[str] = ..., fail_fast: bool = ...) -> str: ...
